### ISSUE TITLE
【7月10日交付】demo PocketPhoenix

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#11]
不要求报告，只要求实际demo。

http://www.speech.cs.cmu.edu/pocketsphinx/

有现成的app代码。要求有能力改。安卓开发部分自学。

7月6日左右讨论，7月10日交付demo

**Comment by whang2017** [comment]
已经能改进已有声学模型

**Comment by whang2017** [comment]
已将文件pr

**Comment by lazyparser** [comment]
已经阅读。 nice work。

报告需要更新一下，在前面添加一下，当只有一台ubuntu/android干净机器的时候，是如何一步步跑起来demo的。这个过程可以是直接贴一个能work的链接，然后描述一下注意事项和可能的坑。

**Comment by whang2017** [comment]
以按照要求更新

**Comment by lazyparser** [comment]
已经完成，LGTM
