### ISSUE TITLE
【7月13日交付】Demo 小米的 MACE 框架

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#12]
https://github.com/XiaoMi/mace

Mobile AI Compute Engine (or MACE for short) is a deep learning inference framework optimized for mobile heterogeneous computing platforms. The design focuses on the following targets:

看着性能强劲。在 TX1 TX2 RK3399等设备上测试一下看看。

要求有demo、性能测评报告。7月10日demo，7月13日测评结果出来。

**Comment by lazyparser** [comment]
Hi 这个进展如何？

**Comment by beijinggongye** [comment]
这个项目目前正在做

**Comment by lazyparser** [comment]
转入内部管理工具
