### ISSUE TITLE
【7月11日交付】调研 mycroft.ai 跑起来 demo 给一份评估报告

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#3]
Mycroft AI
Open Source Voice Assistant
调研一下，给一份评估报告，推送到 weloveinterns。
7月11日截止；要求深度就是7月11号到什么程度就什么程度 (^_^)

报告用 markdown 形式提交到 weloveinterns 的 reports 目录下，PR

内容要求：是什么，做什么，能不能跑起来，怎么用；你觉得有没有用，后续可能的工作和机会。

Demo 要求：跑起来，demo。

**Comment by lazyparser** [comment]
Hi 目前进展如何？

这个任务截止到7月13日，无论进展如何，完成报告并提交。

**Comment by willionZS** [comment]
@lazyparser 删删改改，刚提交完老师，您看一下是否需要补充别的什么

**Comment by lazyparser** [comment]
OK
