### ISSUE TITLE
【7月20日交付】调研 Tensorflow.js 的开发现状并在TX1/TX2上进行测试，评测性能，撰写分析报告

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#4]
要求能够完成MNIST以及更加复杂一些的模型（YOLO or SSD？）的性能测评和准确度测评的工作。7月20日左右能够进行演示。分析报告提交到 weloveinterns

**Comment by lazyparser** [comment]
报告可以很简单。要求 demo 起来。

**Comment by liu-yichang** [comment]
还未开始任务，计划本周开始着手此任务

**Comment by lazyparser** [comment]
设备已经就绪，可以找徐健

**Comment by liu-yichang** [comment]
还在配置TensorFlow.js本地运行环境，打算在搞不出来，放弃在本地运行的方法。换别的方法执行代码。

**Comment by lazyparser** [comment]
转入内部管理工具
