### ISSUE TITLE
【7月20日交付】Demo 在TX1/TX2上运行起来 GluonCV 0.2

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#5]
目标是能够在TX1/TX2运行起来新发布的 GluonCV 0.2 的相关工作。要求7月20日周例会的时候能够演示。
要求能够有实际的测评数据，同时形成一份报告。

**Comment by liu-yichang** [comment]
本周进展：Gluoncv 官网上图像分类方向除了在ImageNet上训练自己的模型没有跑之外，其余的.py文件跑通。
问题：代码看的不是很懂，模型大部分不懂。相当于就是跑通了代码。
            在CPU上跑的程序，有些程序运行时间过于长。

**Comment by lazyparser** [comment]
能跑通代码 👍

模型一个一个看

**Comment by liu-yichang** [comment]
本周进展：GluonCV  demo运行完毕，报告还未写，打算在板子上测试后写。

**Comment by lazyparser** [comment]
下周一可以开始测

**Comment by lazyparser** [comment]
转入内部管理工具
