### ISSUE TITLE
【7月13日交付】Demo 在NUC（x86）上运行起来 GluonCV 0.2

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#6]
目标是能够在NUC上运行起来新发布的 GluonCV 0.2 的相关工作。要求7月20日周例会的时候能够演示。

**Comment by lazyparser** [comment]
@Calsia 在自己笔记本上能够跑起来就可以，最好是NV显卡，没有的话就CPU；不用担心演示的问题，我们到时候可以远程演示。

**Comment by Calsia** [comment]
运行GLuonCV部分分类算法，待解决将Gpu程序运行在cpu上的更给

**Comment by lazyparser** [comment]
明天提交报告

**Comment by Calsia** [comment]
已经提交了，是交错库了吗

**Comment by lazyparser** [comment]
看到了PR，正确的库，nice job (^o^)/

下午我们找时间讨论一下。我有空约你，2点左右。

**Comment by lazyparser** [comment]
已经 merge。这个 issue 已经完成。我关闭了。

**Comment by Calsia** [comment]
好
