### ISSUE TITLE
【7月13日】调研 SQuAD 2.0，demo，提交分析报告

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#7]
入门级介绍，告诉听众这是什么，为什么有，历史背景，以及发展。

demo 级别，找到可以demo的开源工作，并跑起来。能够现场演示。

分析报告，页数不限，提交到weloveinterns

预期能够在7月13日完成并能够有一个简单的针对 SQuAD/SQuAD 2.0 的问答内容的demo。7月20日之前完成报告，并提交 weloveinterns。

**Comment by beijinggongye** [comment]
嗯嗯收到

**Comment by lazyparser** [comment]
根据实习生感兴趣方向的不同，重新调整

**Comment by beijinggongye** [comment]
今天跑了一下找到的demo，之前这个demo代码放到pycharm里面一直有错误，现在已经解决了大部分错误。不过还有一些报错。

**Comment by lazyparser** [comment]
报告进展需要更加具体一些：例如，找到的demo是什么（链接）；有错误，是什么错误，是否解决，是否需要我帮助？

如果需要我帮助的报错信息，直接贴截图给我，在q站上问或者在github上问。

**Comment by lazyparser** [comment]
转入内部管理工具
