### ISSUE TITLE
【7月20日交付】在TX1/TX2上运行 OpenPose，测评性能并形成报告

### ISSUE THREAD

**Issue by lazyparser** [DroidAITech/weloveinterns#9]
https://github.com/CMU-Perceptual-Computing-Lab/openpose

demo 要求能够现场演示。

分析报告要求能够给出具体性能数据，在不同输入情况下。

不要求讲清楚原理。

7月20日现场演示；7月27日前交付到weloveinterns

**Comment by lazyparser** [comment]
@Xiaoxuxiaoxu 设备找常总要；配置Google搜索；代码在GitHub上；一开始会遇到比较多的坑，就是不停的 try

**Comment by Xiaoxuxiaoxu** [comment]
好的

**Comment by lazyparser** [comment]
设备已经就绪，下周一可以开始了。

**Comment by Xiaoxuxiaoxu** [comment]
closes #9

**Comment by lazyparser** [comment]
转入内部管理工具
